name: fun_prize
description: Fun prize mobile application
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  flutter_form_builder: ^3.5.4
  cloud_firestore: ^0.12.9+4
  duration: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Bold.ttf