name: fun_prize
description: Fun prize mobile application
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  flutter_form_builder: ^3.8.2
  cloud_firestore: ^0.13.4+2
  duration: ^2.0.11
  fluttertoast: ^4.0.1
  cached_network_image: ^2.1.0+1
  flutter_facebook_login: ^3.0.0
  flutter_sticky_header: ^0.4.2
  collection: ^1.14.11
  flutter_staggered_grid_view: ^0.3.0
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/placeholder.jpeg
    - assets/category-icon.png
    - assets/gift.png

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Bold.ttf