name: fun_prize
description: Fun prize mobile application
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1
  flutter_form_builder: ^3.5.4
  cloud_firestore: ^0.12.9+4
  duration: ^2.0.8
  flame: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/running-character.png
    - assets/images/backgrounds/city01.png

    - assets/images/character/running/0.png
    - assets/images/character/running/1.png
    - assets/images/character/running/2.png
    - assets/images/character/running/3.png
    - assets/images/character/running/4.png
    - assets/images/character/running/5.png

    - assets/images/character/jumping/0.png
    - assets/images/character/jumping/1.png
    - assets/images/character/jumping/2.png
    - assets/images/character/jumping/3.png
    - assets/images/character/jumping/4.png
    - assets/images/character/jumping/5.png
    - assets/images/character/jumping/6.png
    - assets/images/character/jumping/7.png

    - assets/images/character/idle/0.png
    - assets/images/character/idle/1.png
    - assets/images/character/idle/2.png
    - assets/images/character/idle/3.png
    - assets/images/character/idle/4.png
    - assets/images/character/idle/5.png
    - assets/images/character/idle/6.png
    - assets/images/character/idle/7.png
    - assets/images/character/idle/8.png
    - assets/images/character/idle/9.png
    - assets/images/character/idle/10.png
    - assets/images/character/idle/11.png
    - assets/images/character/idle/12.png
    - assets/images/character/idle/13.png
    - assets/images/character/idle/14.png
    - assets/images/character/idle/15.png
    - assets/images/character/idle/16.png
    - assets/images/character/idle/17.png
    - assets/images/character/idle/18.png
    - assets/images/character/idle/19.png
    - assets/images/character/idle/20.png
    - assets/images/character/idle/21.png
    - assets/images/character/idle/22.png
    - assets/images/character/idle/23.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Bold.ttf